### PR TITLE
EZ grammar

### PR DESCRIPTION
**Pull request by zshoals**
Quick one time edit pass over the readme because I felt like it. You will still need to make informational improvements.

This edit (hopefully) does not change any of the information conveyed. In any place where I'm unsure of the intent of the instructions, I made no change.

I'd highly recommend rewriting the Textures and Gradients section. The intent of it is quite unclear, unfortunately, and I was not able to make any serious adjustments to it.

### CODE REVIEW

**Comment by nanjizal** [comment]
Thanks will take a look tomorrow I think I just wanted to get some ideas down, it's terrible grammar I need to rethink explaining the details, I was just glad my code was working well with interleave, I should take more time to get my grammar correct.

**Comment by nanjizal** [comment]
@zshoals I have decided that the readme was not useful in it's current form.
I am considering better approaches maybe with more diagrams less text, but I am very greatful for you taking the time to edit, your feedback made me realize it was not really suitable.

**Comment by zshoals** [comment]
No problem, I understand and it doesn't bother me. I more or less did it for fun since I enjoy editing things from time to time. Good luck with the next version of it.

**Comment by nanjizal** [comment]
zshoals I have created a git organisation and started adding demos, I have linked the git organisation to this readme. I think once I have enough it should be clearer to just put together an overview.

**Pull request closed without merging**
